### ISSUE TITLE
db initialization hint

### ISSUE THREAD

**Issue by vitaly-t** [GrumpyPants/OpenMicNightServer#1]
I was just looking at your code:

``` js
var pgp = require('pg-promise');
var connectionString = {
    host: 'localhost', // server name or IP address;
    port: 5432,
    database: 'openmicnight',
    user: 'openmicer',
    //password: 'user_password'
};
var db = pgp(connectionString); // this is wrong;
var db = db(connectionString);
```

You are missing the initialization logic for the pg-promise library. The right usage is:

``` js
var options = {
    // pg-promise initialization options;
    // see: https://github.com/vitaly-t/pg-promise#initialization-options
};
var pgp = require('pg-promise')(options);
var db = pgp(connection);
```

**Comment by davidlivingrooms** [comment]
Hi Vitaly,
    Thank you very much for your help. I have updated my code to pass in
the initialization options. I'm enjoying your pg-promise library very much
so thank you for working on it and for pointing out my issue.

-david

**Comment by vitaly-t** [comment]
You are welcome! :)

**Comment by vitaly-t** [comment]
For the code like you have here: https://github.com/GrumpyPants/OpenMicNightServer/blob/5cceccc4b6c02baf76514dd5472fe83694bf82bc/routes/index.js

You will find it much more fun and easier to read, if you:
- Place SQL into external files, using [QueryFiles](http://vitaly-t.github.io/pg-promise/QueryFile.html)
- Switch to [Named Parameters](https://github.com/vitaly-t/pg-promise#named-parameters) for variables.

**Comment by davidlivingrooms** [comment]
Sounds good. I'll take a look at QueryFiles and make the move to named parameters. Thanks.

**Comment by vitaly-t** [comment]
@GrumpyPants that's a loose promise request: https://github.com/GrumpyPants/OpenMicNightServer/blob/c26aa454a4762fe1262c19294af5ebed3c189565/routes/index.js#L219

Which may produce unexpected results. You should fix that, and move the entire loop into a transaction ;)
